language: node_js
install:
- docker-compose build
- npm run lint
- npm run build:front
- npm run build
- npm run typeorm:run
- npm run test:cov
- npm install pm2 -g
- git reset --hard
- npm run pm2 deploy ecosystem.config.js production
node_js:
- 12.18.3
before_install:
- openssl aes-256-cbc -K $encrypted_12ce2cd59fcc_key -iv $encrypted_12ce2cd59fcc_iv
  -in key.enc -out key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./key
- ssh-add ./key