language: node_js

install:
    - docker-compose up -d
    - npm install
    - npm run lint
    - npm run build
    - npm run build:front:prod
    - npm run test
    - npm run typeorm:generate
    - npm run typeorm:run

node_js:
  - "12.18.3"