language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in key.enc -out key.txt -d
install:
- docker-compose up -d
- npm install
- npm run lint
- npm run build:front
- npm run build
- npm run typeorm:run
- npm run test:cov
- npm install pm2 -g
- npm run pm2 deploy ecosystem.config.js production setup
node_js:
- 12.18.3
