language: node_js
install:
- docker-compose up -d
- npm install
- npm run lint
- npm run build:front
- npm run build
- npm run typeorm:run
- npm run test:cov
- npm install pm2 -g
- npm run pm2 deploy ecosystem.config.js production setup
node_js:
- 12.18.3
before_install:
- openssl aes-256-cbc -K $encrypted_12ce2cd59fcc_key -iv $encrypted_12ce2cd59fcc_iv
  -in key.txt.enc -out key.txt -d
