version: '3.7'

services:
  main:
    image: main
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 2121:2121
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres_db

volumes:
  database-data:
